### ISSUE TITLE
Frontend Theme not found

### ISSUE THREAD

**Issue by Wipsly** [ricomonster/journal-blogging-platform#12]
Hello,

I really like this app :-) 

The backend works great, but the frontend theme is missing. (journal.dev is my laravel homestead path)

```
  <link href="http://journal.dev/themes/casper/assets/css/screen.css" rel="stylesheet"/>
```

When i try to open the css file in the browser i get the following error.

The requested URL /themes/casper/assets/css/screen.css was not found on this server.´

**Comment by ricomonster** [comment]
@Wipsly sorry for the late reply. make sure to create a symlink of the themes folder to the public folder. i know by default

**Comment by ricomonster** [comment]
i have a new commit concerning this issue, i created a gulp task to copy assets from the themes folder (commit #27) and be put in the public folder. it is currently not available in the master branch and but i'll release it soon.
